version: '3.8'
services:
  triangle-classification-api:
    build:
      context: ..
      dockerfile: containers/Dev.Dockerfile
    env_file:
      - ../env/dev.env
    volumes:
      - ../src:/var/api/
      - ../tests:/var/testapi/
    ports:
      - "8000:8000"
    depends_on:
      db-mysql:
        condition: service_healthy

  db-mysql:
      image: mysql:8.3.0
      restart: always
      hostname: db-mysql
      container_name: db-mysql
      env_file:
        - ../env/dev.env
      ports:
        - '3306:3306'
      expose:
        - '3306'
      volumes:
        - ../db:/var/lib/mysql
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
