version: '3.8'
services:
  triangle-classification-api:
    build:
      context: ..
      dockerfile: containers/Dev.Dockerfile
    env_file:
      - ../env/dev.env
    volumes:
      - ../src:/var/api/
      - ../tests:/var/testapi/
    ports:
      - "8000:8000"
