AWS_DEFAULT_REGION = "<choose a region>"
AWS_ACCESS_KEY_ID = "<IAM access key id>"
AWS_SECRET_ACCESS_KEY = "<IAM access key id>"
RDS_DATABASE = "<database name>"
RDS_USER = "<database user>"
RDS_PASSWORD = "<database password>"
